### ISSUE TITLE
How to CORS in Lumen 

### ISSUE THREAD

**Issue by loxK** [fruitcake/php-cors#18]
Hello I switched to **Lumen 9.1.6**. I had composer saying that [laravel-cors](https://github.com/fruitcake/laravel-cors) has to be replaced. Currently, I have in app.php :

```
<?php

$app->configure('cors');

$app->middleware([
    Fruitcake\Cors\HandleCors::class,
]);

$app->register(Fruitcake\Cors\CorsServiceProvider::class);
```

I have replaced `\Fruitcake\Cors\HandleCors::class`, with `\Illuminate\Http\Middleware\HandleCors::class` but what about the service provider ?

**Comment by rahmatik1010** [comment]
+1 I've same problem

**Comment by barryvdh** [comment]
I'm sorry, Lumen is not supported. I think you can keep using laravel-cors probably?
