### ISSUE TITLE
Always add Vary header with Origin 

### ISSUE THREAD

**Issue by yinheli** [fruitcake/php-cors#24]
After enabling the CORS middleware in Laravel, it was found that the "Vary: Origin" header is always added regardless of whether it is a CORS request or not. 

I don't think it is necessary if it is not a CORS request. 

https://github.com/fruitcake/php-cors/blob/v1.3.0/src/CorsService.php#L218

**Comment by barryvdh** [comment]
The Vary header is there to make sure that the response is only cached for that specific Origin. If it does not have an Origin header, it needs to return a different response than when it has an Origin that is allowed. If you allow all origins (wildcard) it will always add that, and does not need the Vary header. If you have just 1 allowed origin, that's also the case. But for multiple origins,  we need to make sure it does not get cached for different origins, so the header is added always.

**Comment by yinheli** [comment]
More information refers to the comments of PR https://github.com/fruitcake/php-cors/pull/25
