### ISSUE TITLE
dev-master/1.3.x-dev Version Causes Issues with Default Laravel Installation

### ISSUE THREAD

**Issue by Al-rimi** [fruitcake/php-cors#31]
In the default Laravel Installation `$ composer create-project laravel/laravel `:

```
    - laravel/framework[v11.9.0, ..., v11.33.2] require fruitcake/php-cors ^1.3 -> found fruitcake/php-cors[dev-master, 1.3.x-dev (alias of dev-master)] but it does not match your minimum-stability.
```

While it is possible to work around this by adjusting `minimum-stability` or using specific package configurations, this issue impacts a smooth out-of-the-box experience for Laravel users, might also confuse users who aren’t familiar with Composer's stability settings.

Thank you for your attention to this matter! Please let me know if there’s anything I can do to assist further.

**Comment by barryvdh** [comment]
Are you using the default packagist repo? 1.3.0 is stable and tagger.

**Comment by Al-rimi** [comment]
It turns out the issue was related to the China mirror I am using (https://mirrors.aliyun.com/composer) after switching back to (https://repo.packagist.org), the problem was resolved, and the fruitcake/php-cors package version v1.3.0 was installed without any issues.

Thanks again.
